apiVersion: k8sdb.com/v1beta1
kind: DatabaseSnapshot
metadata:
  name: snapshot-xyz
  labels:
    "k8sdb.com/kind": "Elastic"
spec:
  DatabaseName: elasticsearch-demo
  BucketName: ""
  StorageSecret:
    SecretName: ""
