apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: db-elasticsearch-demo
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      k8sdb.com/type: elasticsearch
      db.appscode.com/name: elasticsearch-demo
  serviceName: governing-elasticsearch
  template:
    metadata:
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "discover",
            "image": "appscode/k8ses:0.1",
            "imagePullPolicy": "IfNotPresent",
            "args": ["discover", "--service=elasticsearch-demo"],
            "env": [
              {
                "name": "POD_NAME",
                "valueFrom": {
                  "fieldRef": {
                    "apiVersion": "v1",
                    "fieldPath": "metadata.name"
                  }
                }
              }
            ],
            "volumeMounts": [
              {
                "name": "discovery",
                "mountPath": "/tmp/discovery"
              }
            ]
          }
        ]'
      labels:
        k8sdb.com/type: elasticsearch
        db.appscode.com/name: elasticsearch-demo
    spec:
      containers:
      - image: appscode/elasticsearch:2.3.1-v2.2
        imagePullPolicy: IfNotPresent
        name: pg-test
        ports:
        - containerPort: 9200
          name: http1
          protocol: TCP
        - containerPort: 9300
          name: http2
          protocol: TCP
        volumeMounts:
        - name: discovery
          mountPath: /tmp/discovery
      volumes:
      - name: discovery
        emptyDir: {}
