apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: k8sdb-elasticsearch-demo
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      k8sdb.com/type: elasticsearch
      elastic.k8sdb.com/name: elasticsearch-demo
  serviceName: governing-elasticsearch
  template:
    metadata:
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "discover",
            "image": "k8sdb/k8s-es:canary",
            "imagePullPolicy": "IfNotPresent",
            "args": ["discover", "--service=elasticsearch-demo"],
            "env": [
              {
                "name": "POD_NAME",
                "valueFrom": {
                  "fieldRef": {
                    "apiVersion": "v1",
                    "fieldPath": "metadata.name"
                  }
                }
              }
            ],
            "volumeMounts": [
              {
                "name": "discovery",
                "mountPath": "/tmp/discovery"
              }
            ]
          }
        ]'
      labels:
        k8sdb.com/type: elasticsearch
        elastic.k8sdb.com/name: elasticsearch-demo
    spec:
      containers:
      - image: k8sdb/elasticsearch:canary
        imagePullPolicy: IfNotPresent
        name: elasticsearch
        env:
        - name: CLUSTER_NAME
          value: elasticsearch-demo
        ports:
        - containerPort: 9200
          name: api
          protocol: TCP
        - containerPort: 9300
          name: tcp
          protocol: TCP
        volumeMounts:
        - name: discovery
          mountPath: /tmp/discovery
        - name: volume
          mountPath: /var/pv
      volumes:
      - name: discovery
        emptyDir: {}
      - name: volume
        emptyDir: {}
