apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-demo
  namespace: default
spec:
  ports:
  - name: api
    port: 9200
    protocol: TCP
    targetPort: api
  - name: tcp
    port: 9300
    protocol: TCP
    targetPort: tcp
  selector:
    elastic.kubedb.com/name: elasticsearch-demo
