apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-demo
  namespace: default
spec:
  ports:
  - name: http1
    port: 9200
    protocol: TCP
    targetPort: 9200
  - name: http2
    port: 9300
    protocol: TCP
    targetPort: 9300
  selector:
    elastic.k8sdb.com/name: elasticsearch-demo
